# Generated by Django 5.2.6 on 2025-10-23 11:46

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('date_of_death', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='author_name_case_insensitive_unique', violation_error_message='Nome já existe (comparação insensível a maiúsculas/minúsculas)')],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Digite o título do livro (ex: O Senhor dos Anéis)', max_length=50)),
                ('summary', models.TextField(help_text='Digite um resumo do livro', max_length=150)),
                ('isbn', models.CharField(help_text='Número ISBN de 13 caracteres <a href="https://www.isbn-international.org/content/what-isbn">ISBN</a>', max_length=13, unique=True, verbose_name='ISBN')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.author')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='BookInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID único para esta instância específica de livro em toda a biblioteca', primary_key=True, serialize=False)),
                ('due_back', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('m', 'Manutenção'), ('o', 'Emprestado'), ('a', 'Disponível'), ('r', 'Reservado')], default='m', help_text='Disponibilidade do livro', max_length=1)),
                ('imprint', models.CharField(help_text='Informações sobre a editora ou impressão', max_length=255)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalog.book', verbose_name='Livro')),
                ('borrower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['due_back'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Digite um gênero de livro (ex: Ficção Científica, Poesia Francesa etc.)', max_length=200, unique=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='genre_name_case_insensitive_unique', violation_error_message='Gênero já existe (comparação insensível a maiúsculas/minúsculas)')],
            },
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(to='catalog.genre'),
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='language_name_case_insensitive_unique', violation_error_message='Idioma já existe (comparação insensível a maiúsculas/minúsculas)')],
            },
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalog.language'),
        ),
        migrations.AddConstraint(
            model_name='book',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('title'), name='book_title_case_insensitive_unique', violation_error_message='Livro já existe (comparação insensível a maiúsculas/minúsculas)'),
        ),
    ]
